version: "3.3"
services:
  nginx: 
    build: ./nginx
    # image: nginx:latest
    image: masarity/autoloading-nginx:latest
    restart: always
    ports:
      - "80:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - host-networks
    depends_on:
      - flask
  flask:
    build: ./autoloading-backend
    image: masarity/autoloading-backend:latest
    restart: always
    networks:
      - host-networks
    depends_on:
      - db
    volumes:
      - ./autoloading-backend:/usr/src/app/
  db:
    build: ./db
    image: masarity/autoloading-db:latest
    restart: always
    networks:
      - host-networks
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d/:ro
      - mysql:/var/lib/mysql 

networks:
  host-networks:
    driver: bridge

volumes:
  mysql:
